In [17]:
import pandas as pd

In [18]:
def convert_salary_to_float(salary):
    return float("".join(salary.split(",")))

In [19]:
data = pd.read_csv("Employee_2.csv")
data["Annual_Salary"] = data["Annual_Salary"].apply(convert_salary_to_float)

In [20]:
data.head()

,Department,Employee_Status,Gender,City,Age,Annual_Salary,Hire_Date,Termination_Date,Rate_1,Employee_Code,State_Filing_Status,Position_Code,EEO1_Ethnicity
0,136,Active,Female,SOUTH SAN FRANCISCO,45,32760.0,09/15/2015,00/00/0000,15.75,A0V4,M,TM2C,Hispanic or Latino
1,136,Active,Female,SOUTH SAN FRANCISCO,46,43680.0,03/15/2010,00/00/0000,21.00,A2HD,S,TL2C,Hispanic or Latino
2,136,Active,Female,SOUTH SAN FRANCISCO,43,31720.0,08/03/2017,00/00/0000,15.25,A6WH,S,TM2C,Hispanic or Latino
3,136,Active,Female,PACIFICA,40,31200.0,02/14/2018,00/00/0000,15.00,A7M0,S,TM2C,Asian
4,136,Active,Female,S SAN FRANCISCO,57,33280.0,07/05/2018,00/00/0000,16.00,A82Q,S,TM2C,Hispanic or Latino

In [27]:
def gender_feature_function(row):
    if row["Gender"] == "Female":
        return 0
    return 1

In [31]:
def salary_feature_function(row, mean, stdev):
    salary = row["Annual_Salary"]
    return (salary-mean)/stdev

In [35]:
def still_employed(row):
    if str(row["Termination_Date"]) == "00/00/0000":
        return 0
    else:
        return 1

In [32]:
mean_salary = data["Annual_Salary"].mean()
stdev_salary = data["Annual_Salary"].std()

In [39]:
X = []
y = []
for index, row in data.iterrows():
    feature_vector = []
    feature_vector.append(gender_feature_function(row))
    feature_vector.append(salary_feature_function(row, mean_salary, stdev_salary))
    X.append(feature_vector)
    y.append(still_employed(row))

In [40]:
X

[[0, 1.5188969505816783],
 [0, 3.8192086840696264],
 [0, 1.2998196426304451],
 [0, 1.1902809886548287],
 [0, 1.628435604557295],
 [0, 1.2998196426304451],
 [1, 2.5047448363622276],
 [1, 1.2998196426304451],
 [1, 1.2998196426304451],
 [1, 1.4093582966060618],
 [0, 1.2998196426304451],
 [1, 1.2998196426304451],
 [1, 1.1902809886548287],
 [0, 1.1902809886548287],
 [1, -1.8768013226624356],
 [1, -1.8768013226624356],
 [1, -1.7672626686868191],
 [1, -1.548185360735586],
 [0, -1.6577240147112025],
 [1, -1.000492090857503],
 [1, -1.4386467067599693],
 [1, -1.3291080527843528],
 [0, -0.23372151302818697],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [0, -0.5623374749550367],
 [1, -0.5623374749550367],
 [0, -0.014644205076953798],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [0, -1.6577240147112025],
 [1, -1.548185360735586],
 [0, -0.12418285905257039],
 [1, -1.6577240147112025],
 [0, -1.6577240147112025],
 [0, -1.548185360735586],
 [1, -1.6577240147112025],
 [0, -1.6577240147112025],
 [1, -1.6577240147112025],
 [1, -1.6577240147112025],
 [1, -1.4386467067599693],
 [1, -1.6577240147112025],
 [1, -1.6577240147112025],
 [0, -1.548185360735586],
 [1, -1.4386467067599693],
 [0, -0.23372151302818697],
 [1, -1.6577240147112025],
 [0, -1.548185360735586],
 [0, -1.4386467067599693],
 [1, -1.4386467067599693],
 [1, -1.3291080527843528],
 [1, -1.3291080527843528],
 [0, 0.09489444889866279],
 [0, -0.5623374749550367],
 [1, -1.3291080527843528],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [0, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [0, -0.5623374749550367],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [1, -0.5623374749550367],
 [1, 0.5330490648011291],
 [1, 1.1902809886548287],
 [1, -0.3432601670038035],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [0, -0.5623374749550367],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [0, -0.5623374749550367],
 [0, 0.9712036807035954],
 [0, -0.5623374749550367],
 [1, -0.014644205076953798],
 [0, -0.5623374749550367],
 [0, 0.5330490648011291],
 [1, -0.5623374749550367],
 [1, -0.5623374749550367],
 [0, -0.3432601670038035],
 [1, -0.3432601670038035],
 [0, -0.5623374749550367],
 [1, -0.3432601670038035],
 [0, -0.5623374749550367],
 [1, -0.3432601670038035],
 [1, -0.3432601670038035],
 [1, -0.5623374749550367],
 [0, -0.5623374749550367],
 [1, 1.4093582966060618],
 [1, -0.3432601670038035],
 [1, -0.3432601670038035],
 [1, 0.5330490648011291],
 [0, -0.014644205076953798],
 [0, -0.3432601670038035],
 [0, -0.12418285905257039],
 [0, -0.12418285905257039],
 [1, 1.4093582966060618],
 [1, 0.09489444889866279],
 [0, -0.12418285905257039],
 [0, 0.5330490648011291],
 [0, 0.5330490648011291],
 [1, 1.1902809886548287],
 [1, 0.09489444889866279],
 [1, 0.09489444889866279],
 [1, 0.09489444889866279],
 [1, -0.12418285905257039],
 [0, 0.09489444889866279],
 [1, 0.09489444889866279],
 [0, 0.09489444889866279],
 [1, 0.20443310287427938],
 [0, 0.09489444889866279],
 [0, 0.20443310287427938],
 [1, 0.09489444889866279],
 [0, 0.09489444889866279],
 [0, 0.09489444889866279],
 [0, 0.313971756849896],
 [1, 0.09489444889866279],
 [0, 0.313971756849896],
 [1, 0.313971756849896],
 [1, 0.5330490648011291],
 [0, 0.5330490648011291],
 [0, 0.5330490648011291],
 [1, 0.5330490648011291],
 [0, 1.1902809886548287],
 [0, 0.5330490648011291],
 [0, 1.1902809886548287],
 [0, 0.5330490648011291],
 [0, 0.5330490648011291],
 [1, 0.5330490648011291],
 [1, 0.5330490648011291],
 [1, 1.1902809886548287],
 [0, 0.5330490648011291],
 [1, 0.5330490648011291],
 [0, 0.5330490648011291],
 [1, 0.5330490648011291],
 [0, 0.5330490648011291],
 [1, 0.5330490648011291],
 [1, 0.5330490648011291],
 [0, 0.5330490648011291],
 [1, 0.5330490648011291],
 [1, 1.1902809886548287],
 [1, 1.1902809886548287],
 [1, 1.1902809886548287],
 [1, 1.4093582966060618],
 [0, 1.1902809886548287],
 [0, 1.1902809886548287],
 [0, 1.1902809886548287],
 [1, 1.1902809886548287],
 [0, 1.4093582966060618],
 [0, 1.1902809886548287],
 [1, 1.1902809886548287],
 [1, 1.1902809886548287],
 [0, 1.1902809886548287],
 [0, 1.1902809886548287],
 [0, 1.1902809886548287],
 [1, 1.1902809886548287],
 [1, 1.1902809886548287],
 [1, 1.1902809886548287],
 [0, 1.1902809886548287],
 [1, 1.1902809886548287],
 [1, 1.1902809886548287],
 [1, 1.1902809886548287],
 [1, 1.2998196426304451],
 [1, 1.1902809886548287],
 [1, 1.2998196426304451],
 [0, -0.12418285905257039],
 [0, -0.3432601670038035]]

In [41]:
y

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0]